#!/bin/bash

source ddns.conf || { echo "Error: config file is not found."; exit 1; }

[[ -z "$ipv6" || -z "$ipv4" ]] && { echo 'Error: ipv6 or ipv4 is empty!'; exit 1; }

# duckdns.org
_dom=`echo $hostname_duck | cut -d'.' -f1`
uurl_duck="https://www.duckdns.org/update?domains=$_dom&token=$token_duck&ipv6=$ipv6"
#uurl_duck="https://www.duckdns.org/update?domains=$_dom&token=$token_duck&ipv6=$ipv6&verbose=true"

# no-ip.com - no ipv6 support/30 day expire
uurl_noip="https://$username_noip:$password_noip@dynupdate.no-ip.com/nic/update?hostname=$hostname_noip&myip=$ipv4"

# freedns.afraid.org - ipv6 only
uurl_afr="https://freedns.afraid.org/dynamic/update.php?$tokenAAAA_afr&address=$ipv6"


function restart_apache() {
  #echo 'Restarting apache'
  if [[ -e /usr/sbin/apache2 ]]; then
    if [[ -f /run/apache2/apache2.pid ]]; then
      if [[ -d /run/systemd/system ]]; then
	systemctl restart --no-block apache2.service >/dev/null 2>&1 || true
      else
	/usr/sbin/invoke-rc.d apache2 restart >/dev/null 2>&1 || true
      fi
    fi
  fi
}

function update_freedns1() {
  local tmpfile=/tmp/ip6tmp_afr
  #echo 'Updating freedns.afraid.org'
  if [[ -r $tmpfile ]]; then
    #echo 'tmpfile exists'
    if [[ "$ipv6" != "$(cat $tmpfile)" ]]; then
      #echo 'not equal'
      curl -m 30 -k $uurl_afr
      echo $ipv6 > $tmpfile
    #else
      #echo 'equals'
    fi
  else
    #echo 'tmpfile does not exist'
    curl -m 30 -k $uurl_afr
    echo $ipv6 > $tmpfile
  fi
}

function update_noip2() {
  local tmpfile=/tmp/ip6tmp_noip
  #echo 'Updating no-ip.com'
  if [[ -r $tmpfile ]]; then
    if [[ "$ipv4" != "$(cat $tmpfile)" ]]; then
      curl -m 30 -A $useragent_noip -k $uurl_noip
      echo $ipv4 > $tmpfile
    fi
  else
    curl -m 30 -A $useragent_noip -k $uurl_noip
    echo $ipv4 > $tmpfile
  fi
}

function update_duckdns3() {
  local tmpfile=/tmp/ip6tmp_duck
  #echo 'Updating duckdns.org'
  if [[ -r $tmpfile ]]; then
    if [[ "$ipv6" != "$(cat $tmpfile)" ]]; then
      RESP=$(curl -s -m 30 -k $uurl_duck)
      if [[ $? -eq 0 ]]; then
        if [[ "$RESP" == 'OK' ]]; then
          echo $ipv6 > $tmpfile
          restart_apache
	fi
      fi
    fi
  else
    RESP=$(curl -s -m 30 -k $uurl_duck)
    if [[ $? -eq 0 ]]; then
      if [[ "$RESP" == 'OK' ]]; then
	echo $ipv6 > $tmpfile
	restart_apache
      fi
    fi
  fi
}


### MAIN PROGRAM ###
#update_freedns1
#update_noip2
update_duckdns3

exit 0
